app:
  port: "8080"

db:
  host: "postgres"
  port: "5432"
  sslmode: "disable"

minio:
  endpoint: "minio:9000"
  port: "9000"
  sslmode: false
  bucketname: "objects"
  ttl: 24h

redis:
  host: "redis"
  port: "6379"
  db: 0

elastic:
  host: "elasticsearch"
  port: "9200"

cache:
  default_ttl: 24h
  counters_ttl: 30s

tokens:
  access_ttl: 720h
  refresh_ttl: 720h
  recovery_ttl: 15m

grpc:
  host: "search-service.zapp.svc.cluster.local"
  integration_port: "50051"
  search_port: "50052"

kafka:
  brokers: ["kafka-0.kafka-headless.zapp.svc.cluster.local:9092"]
  topics: ["tweet-events", "user-events"]
  producer:
    max_retries: 3
  consumer:
    group_id: "search-group"