port: 8080

db:
  host: "localhost"
  port: 5432
  sslmode: "disable"

minio:
  endpoint: "localhost:9000"
  port: 9000
  sslmode: false
  bucketname: "objects"
  ttl: 24h

redis:
  host: "localhost"
  port: 6379
  db: 0

elastic:
  host: "127.0.0.1"
  port: 9200

cache:
  defaultTtl: 24h
  countersTtl: 30s

tokens:
  accessTTL: 720h # Поменять
  refreshTTL: 720h
  recoveryTTL: 15m
