app:
  port: "8080"

db:
  host: "localhost"
  port: "5432"
  sslmode: "disable"

minio:
  endpoint: "localhost:9000"
  port: :9000"
  sslmode: false
  bucketname: "objects"
  ttl: 24h

redis:
  host: "localhost"
  port: 6379
  db: 0

elastic:
  host: "127.0.0.1"
  port: 9200

cache:
  default_ttl: 24h
  counters_ttl: 30s

tokens:
  access_ttl: 720h # Change
  refresh_ttl: 720h
  recovery_ttl: 15m

grpc:
  host: "localhost"
  integration_port: 50051
  search_port: 50052

kafka:
  brokers: ["localhost:9092"]
  topics: ["tweet-events", "user-events"]
  producer:
    max_retries: 3
  consumer:
    group_id: "search-group"